
package bean;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSTurmaService", targetNamespace = "http://bean/", wsdlLocation = "http://localhost:8080/Trabalho_interdisciplinar/WSTurmaService?wsdl")
public class WSTurmaService
    extends Service
{

    private final static URL WSTURMASERVICE_WSDL_LOCATION;
    private final static WebServiceException WSTURMASERVICE_EXCEPTION;
    private final static QName WSTURMASERVICE_QNAME = new QName("http://bean/", "WSTurmaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Trabalho_interdisciplinar/WSTurmaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSTURMASERVICE_WSDL_LOCATION = url;
        WSTURMASERVICE_EXCEPTION = e;
    }

    public WSTurmaService() {
        super(__getWsdlLocation(), WSTURMASERVICE_QNAME);
    }

    public WSTurmaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSTURMASERVICE_QNAME, features);
    }

    public WSTurmaService(URL wsdlLocation) {
        super(wsdlLocation, WSTURMASERVICE_QNAME);
    }

    public WSTurmaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSTURMASERVICE_QNAME, features);
    }

    public WSTurmaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSTurmaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSTurma
     */
    @WebEndpoint(name = "WSTurmaPort")
    public WSTurma getWSTurmaPort() {
        return super.getPort(new QName("http://bean/", "WSTurmaPort"), WSTurma.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSTurma
     */
    @WebEndpoint(name = "WSTurmaPort")
    public WSTurma getWSTurmaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bean/", "WSTurmaPort"), WSTurma.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSTURMASERVICE_EXCEPTION!= null) {
            throw WSTURMASERVICE_EXCEPTION;
        }
        return WSTURMASERVICE_WSDL_LOCATION;
    }

}
